name: Annoy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: ["ubuntu-20.04", "macos-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@v3 # Pull the repository
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install .
      - run: pip install h5py numpy pytest
      - run: pytest -v
